apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: yolomurphy/my-app:b9699f592e30c980f7eb2e7449b1f4f37cf776dc
        ports:
        - containerPort: 3000
