apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: yolomurphy/my-app:678b05463fd6487304d8962453ef528eca0b4464
        ports:
        - containerPort: 3000
