apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: yolomurphy/my-app:28826e7930c3702a244073f87b9b5f0978c5f688
        ports:
        - containerPort: 3000
